# Generated by Django 3.1.1 on 2020-09-12 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlistName', models.CharField(max_length=255, verbose_name='Name of wishlist')),
                ('isSharedToOthers', models.BooleanField(verbose_name='Others can see current wishlist')),
                ('wishlistOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectName', models.CharField(max_length=200, verbose_name='Name of the object')),
                ('objectDescription', models.CharField(max_length=500, verbose_name='Describe of the object')),
                ('reasonToHave', models.CharField(max_length=500, verbose_name='Why do you need this object')),
                ('objectLocation', models.CharField(max_length=500, verbose_name='Where you can find this object')),
                ('requirementsToDo', models.CharField(max_length=500, verbose_name='What you need to do for getting this object')),
                ('wishlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist')),
            ],
        ),
    ]
