# Generated by Django 3.1.1 on 2020-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishobject',
            name='objectDescription',
            field=models.TextField(verbose_name='Describe of the object'),
        ),
        migrations.AlterField(
            model_name='wishobject',
            name='objectLocation',
            field=models.TextField(verbose_name='Where you can find this object'),
        ),
        migrations.AlterField(
            model_name='wishobject',
            name='reasonToHave',
            field=models.TextField(verbose_name='Why do you need this object'),
        ),
        migrations.AlterField(
            model_name='wishobject',
            name='requirementsToDo',
            field=models.TextField(verbose_name='What you need to do for getting this object'),
        ),
    ]
