# Generated by Django 3.1.1 on 2020-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20200912_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlistName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of wishlist'),
        ),
    ]
