# Generated by Django 3.1.1 on 2020-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20200913_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlistName',
            field=models.CharField(max_length=255, verbose_name='Name of wishlist'),
        ),
    ]
