# Generated by Django 3.1.1 on 2020-09-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20200913_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlistOwner',
            new_name='wishlistOwnerID',
        ),
    ]
